### PR TITLE
Add images directly from clipboard

### PR DESCRIPTION
**Pull request by angelformica**
Hello,

First I want to say thank you for this great nova package!

I would like you to consider merging this feature. With this, the user has the ability to add images not only from files, but also from the clipboard directly. Just like Trello does it.

https://drive.google.com/file/d/19Mm29m6_C06TDM5W40KXtt0MhzoXWrJx/view

Best regards,

### CODE REVIEW

**Comment by eboye** [comment]
Love the feature. Looks great! Hope it get merged

**Comment by shirshak55** [comment]
is somebody maintaining fork because it seems its dead already and thats so unfortunate :(

**Comment by bkintanar** [comment]
This looks great. I have a fork that I use for an open issue for Laravel 7 support. I hope the package author merges this.

**Comment by shirshak55** [comment]
@bkintanar can u publish in packagist and give us that? I think its dead so no point now.

**Comment by bkintanar** [comment]
@shirshak55 don't want to get ahead of myself here. The package author's last activity was Feb 19. Maybe he is just on vacation or something.

**Comment by shirshak55** [comment]
@bkintanar i see oct 19 ,2019 for this package. Its more than 6 month so i don't expect him to update again :(

**Comment by bkintanar** [comment]
It says Feb 19, 2020.

image

**Comment by shirshak55** [comment]
if somebody wants to grab this pr and compatibility with latest version u can use my fork.

```
composer require ebess/advanced-nova-media-library
```

Remember medialibrary v8 has some changes which u need to fix. Read upgrade guide of spatie medialibrary.

**Comment by bkintanar** [comment]
@angelformica can you send a PR to https://github.com/bkintanar/advanced-nova-media-library?

**Comment by shirshak55** [comment]
@bkintanar u can merge the pr directly by comparing :) . There is no reason to wait

**Comment by shirshak55** [comment]
@bkintanar is there any problem and directly merging the PR in your repo. Because I did already merged in the fork i used from github directly. But yes I think we should build js ourself as we don't know if it can be trusted.

**Comment by bkintanar** [comment]
@shirshak55 yeah, maybe I'll just try to create a PR from his fork, and then rebuild the js.

**Comment by angelformica** [comment]
Hello, sure, I'll do this later today.

Best regards.

**Comment by bkintanar** [comment]
Thanks @angelformica

**Comment by angelformica** [comment]
@bkintanar Done, I just sent the PR.

Have a nice day!

**Comment by ebess** [comment]
there is one problem with this PR as it seems. if you paste this image, it will paste in every field. a check which field you are hoving is needed tho

**Comment by ebess** [comment]
I updated the code to paste the image only on currently hovered fields. Otherwise this feature is not usable if you have multiple fields on the model. @angelformica good job!

**Pull request merged**
