### PR TITLE
Make cropping by default configurable

### PR DESCRIPTION
**Pull request by jaap**
I was updating a project to the latest version and noticed that all images had crop functionality.
For this project, however, cropping is done in an automated way and not needed. Instead of disabling cropping on all images by hand it would, in this case, be more convenient to alter the default behaviour. This PR makes that default behaviour configurable.

Do you see this as a viable PR @ebess?

### CODE REVIEW

**Comment by bkintanar** [comment]
@jaap can you create a PR to targe 4.x as well?

**Comment by jaap** [comment]
I'm confused, by merging into master and afterwards releasing it would be in 4.0.x would it not?

**Comment by bkintanar** [comment]
apparently not. Ebess is no longer maintaining this package and I can't make 4.x as the default branch. so all PRs should be targeting 4.x in order for it to be released.

--
Bertrand Kintanar
***@***.***

**Comment by jaap** [comment]
@bkintanar like this? https://github.com/ebess/advanced-nova-media-library/pull/350

**Comment by bkintanar** [comment]
Yes. Thank you. I will release it today.

--
Bertrand Kintanar
***@***.***

**Pull request merged**
