### PR TITLE
Fix help text in files

### LINKED ISSUE #208: Cant use Field Help Text in Files
Hi,

Captura de ecrã 2020-10-16, às 14 30 19

In Images works fine, like this
```
Images::make('Images', 'gallery')
->singleMediaRules(['mimetypes:image/jpg,image/jpeg,image/png'])
->help('.jpg, .jpeg or .png'),
```
In Files doesn't work
```
Files::make('File', 'file')
->rules('required')
->singleMediaRules(['mimes:pdf,zip,jpef,jpg,png'])
->help('Pdf, Zip, Jpeg, Jpg, Png'),
```

### PR DESCRIPTION
**Pull request by bcoelhodev**
This PR fix help text in Files.

In Files the help text is not displayed.

Closes #208.

### CODE REVIEW

**Comment by egreca** [comment]
Hi,

I had the same issue and was thinking to make a PR, but then I checked the PR was already created by @bcoelhodev.
It would be very helpful if you merge this PR.

Thank you!

**Comment by chrispage1** [comment]
+1 would like to be merged. Unlike issue #208 I can't seem to use help text anywhere (images, files etc..)

**Comment by bkintanar** [comment]
@bcoelhodev please fix conflict file so I can recheck.

**Comment by bkintanar** [comment]
@bcoelhodev still having merge conflict.

**Comment by bcoelhodev** [comment]
> @bcoelhodev still having merge conflict.

Fixed.

**Pull request merged**
