### PR TITLE
add custom properties functionality

### PR DESCRIPTION
**Pull request by yevhenkoriakin**
example of save file hash custom property with callback

```
Images::make('Field', 'collection')
    ->setCustomProperties(function (Request $request, UploadedFile $file) {
        return [
            'md5_file' => md5_file($file->getRealPath())
        ];
    }),
```

### CODE REVIEW

**Comment by bkintanar** [comment]
@yevhenkoriakin sorry to get back to you so late. Is this still a feature you'd like added in the package?

**Comment by yevhenkoriakin** [comment]
Yes. Adding custom fields via callback function is a very useful thing.

**Comment by yevhenkoriakin** [comment]
> @yevhenkoriakin sorry to get back to you so late. Is this still a feature you'd like added in the package?

Yes. Adding custom fields via callback function is a very useful thing

**Comment by bkintanar** [comment]
@yevhenkoriakin can you check if this PR is still valid, meaning it is still working? Kinda merged couple of PRs lately.

**Comment by bkintanar** [comment]
@yevhenkoriakin can you add entries to the readme for this as well please?

**Comment by bkintanar** [comment]
@yevhenkoriakin, I'm planning on creating a tag soon, let me know if this is something you can do so that we can include it in the release soon.

**Pull request closed without merging**
