### PR TITLE
Removed duplicated help text

### PR DESCRIPTION
**Pull request by Nks**
image

If `->help()` method is used it is showing the help text 2 times.

### CODE REVIEW

**Comment by bendadaniel** [comment]
Merge this PR please

**Comment by bkintanar** [comment]
What does it show in Nova 3? Is this backwards compatible?

**Comment by alexwenzel** [comment]
+1

**Comment by kbellpostman** [comment]
+1

**Comment by joschaefer** [comment]
+1

**Comment by chimit** [comment]
@bkintanar this bug still exists in the latest version (4.0.5).

**Comment by bkintanar** [comment]
thanks @chimit . I think this hasn't been pushed to 4.x branch yet.

**Comment by VGirol** [comment]
Would it be possible to push it to 4.x branch, please ?

**Comment by timersys** [comment]
+1

**Comment by kitro** [comment]
This bug still occurs in 4.0.5
image
image

**Comment by VGirol** [comment]
Would it be possible to push it to 4.x branch, please ?

**Pull request merged**
