### PR TITLE
Frontend side file size and type validation

### PR DESCRIPTION
**Pull request by danielztolnai**
I recently encountered a problem with Nova, where the update form does not handle 413 (Request Entity Too Large) errors and fails silently. To solve the problem, I added options to the Media field so that the user can check the size and type of the files on the frontend side.

I also think that this is a better solution than simply handling the 413, as with the latter the user would still have to wait for the upload to finish, just to realize that the file is above the size limit. This solution gives an almost instant answer to the user and saves the waiting time for them.

This validation can be added to the field in the resource using for example:
- `->setMaxFileSize(4096)` (4 MB limit)
- `->setAllowedFileTypes(['video', 'image/jpeg'])` (only videos and jpeg images)

### CODE REVIEW

**Comment by bkintanar** [comment]
@danielztolnai please squash commit messages.

**Comment by danielztolnai** [comment]
> @danielztolnai please squash commit messages.

Okay, it is now one commit.

**Comment by bkintanar** [comment]
@danielztolnai I see conflicts. can you rebuild js assets please? Sorry, I think this is because I just merged a PR from a different issue.

**Comment by danielztolnai** [comment]
> @danielztolnai I see conflicts. can you rebuild js assets please? Sorry, I think this is because I just merged a PR from a different issue.

I've done the rebuild, now the conflicts should be gone.

**Pull request merged**
