### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected a dependency for the `laravel/framework`. Unless you have a special requirement for depending on the entire Laravel framework, it's recommended to add dependencies for the specific `illuminate` packages instead.

**Comment by fh32000** [comment]
@laravel-shift  Thanks
#379 
@happyDemon @jnbn @Nks @Livijn 
Please merge PR

**Comment by fh32000** [comment]
Anyone who wants to use this library on  Laravel 10 before the version is supported, use this method
in composer js -> require
```
 "require": {
 ....
 ....
        "ebess/advanced-nova-media-library": "dev-l10-compatibility",
        }

```
then in composer js -> repositories
```
    "repositories": {
        "ebess/advanced-nova-media-library": {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/advanced-nova-media-library.git"
        }
    },
```

**Comment by divya-kanak** [comment]
Hello, 

I am still fetching the issue with this project!

I have followed the same steps below:

image


image

Issue :
image

**Comment by divya-kanak** [comment]
Also, To access this repository system ask for PAT(Personal Access Token) of the github. is it inaccessible publically?

https://github.com/laravel-shift/advanced-nova-media-library/tree/l10-compatibility

**Comment by gerardnll** [comment]
> Also, To access this repository system ask for PAT(Personal Access Token) of the github. is it inaccessible publically?
> 
> https://github.com/laravel-shift/advanced-nova-media-library/tree/l10-compatibility

If you do like the last laravel-shift comment, it works perfectly. Watch the repositories key, I didn't do it like @fh32000 said.

**Comment by divya-kanak** [comment]
Hello @gerardnll ,

Can you please guide me how I can use the last laravel-shift comment in composer.json file ?

**Comment by gerardnll** [comment]
> Hello @gerardnll ,
> 
> Can you please guide me how I can use the last laravel-shift comment in composer.json file ?

You have almost already done it. Just fix your 'repositories' property with what is specified [here](https://github.com/ebess/advanced-nova-media-library/pull/374#issuecomment-1408950996).

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/advanced-nova-media-library.git"
        }
    ]
}
```

You have added a key to the object which I don't think is necessary.

**Comment by sajaddp** [comment]
@happyDemon @jnbn @Nks @Livijn

**Comment by bkintanar** [comment]
has anyone tested this in laravel 10 yet?

**Comment by sajaddp** [comment]
@bkintanar 
https://github.com/ebess/advanced-nova-media-library/pull/374#issuecomment-1434500010 worked for me.

**Comment by bkintanar** [comment]
@sajaddp i'm asking so that i can merge and create a tag for it.

**Comment by gerardnll** [comment]
Works good for me

**Comment by ziming** [comment]
Thanks for merging! @bkintanar could you tag a new release as well?

Thank you

**Pull request merged**
