### PR TITLE
Show asterisk after required field label

### PR DESCRIPTION
**Pull request by eimantaaas**

### CODE REVIEW

**Comment by bkintanar** [comment]
@eimantaaas can you push the yarn.lock file as well?

**Comment by eimantaaas** [comment]
@bkintanar sure, but yarn.lock has no changes. Have pushed missing builded file

**Comment by mrdj07** [comment]
This should be merged !

**Comment by mrdj07** [comment]
Woah, reactive, thanks !!

**Comment by bkintanar** [comment]
lol. I'll plan a release this week for the other merged features/fixes.

**Comment by mrdj07** [comment]
Great, thanks ! Fantastic package btw !

**Pull request merged**
