### PR TITLE
Show image dimensions

### PR DESCRIPTION
**Pull request by 0xb4lint**
Added `showDimensions()` function, which calculates width, height and aspect ratio of the image.

Image dimensions

```php
Images::make('Gallery')
    ->showDimensions();
```

### CODE REVIEW

**Comment by ebess** [comment]
@0xb4lint thanks you for great work. i will merge this on master and rebuild assets i'll process the opened prs

**Comment by bernhardh** [comment]
I am on master now, but it doesn't work. Nothing is shown. No error.

**Comment by bernhardh** [comment]
.bmdev-nova-flexible-content

**Comment by bernhardh** [comment]
I am on master now, and nothing of the dimensions are shown. Neither on detail, nor on the form

**Comment by NormanHuth** [comment]
Same here.

**Pull request merged**
