### PR TITLE
Added "mustCrop" to force a user to crop added / selected images.

### PR DESCRIPTION
**Pull request by GarethSomers**
I've added a new feature `mustCrop`.

When enabled any new images added / selected will _force_ the user to crop the image. It will open the cropping modal with the close / cancel / escape functionality disabled. 

This is useful for scenario uploads are in a specific size (and not relying on media conversions).

### Usage
```
Images::make('Image', 'image')->mustCrop()
```

### Notes
I've require 1.1.4+ of Vue JS Clipper to allow the newest cropping settings.

I've also made adjustments to how the cropper modal is display to ensure it doesn't exceed the page dimensions.

### CODE REVIEW

**Comment by bkintanar** [comment]
@GarethSomers can you squash your commits please? Thank you!

**Comment by danielztolnai** [comment]
@bkintanar, I really needed this feature, so I adjusted this PR's branch to the current version and added some extra features (Focusing the update button automatically and allowing the cancel button to work even when `mustCrop` is set.)

If @GarethSomers is okay with it, I can create a PR / you can merge it. (My branch contains the original commits from this PR as I merged @GarethSomers' branch.)

Here is the branch, in case someone wants to check it out: https://github.com/apicore-engineering/advanced-nova-media-library/tree/feature/enforce-cropping

**Comment by GarethSomers** [comment]
Feel free to create your own PR and I'll close this one.

**Comment by GarethSomers** [comment]
Closed in favour of https://github.com/ebess/advanced-nova-media-library/pull/209 👍 👍 👍

**Pull request closed without merging**
