### PR TITLE
Version support Larvel 6.0 | Nova 2.1|2.2

### PR DESCRIPTION
**Pull request by nemrutco**

### CODE REVIEW

**Comment by eimantaaas** [comment]
What about Nova 2.2 ?

**Comment by ragingdave** [comment]
Also I don't know if the php version works like that. Like It's not likely going to pick the right php version constraint to go up against the nova or laravel constraints. It might install, but that doesn't look like it's going to work properly.

**Comment by nemrutco** [comment]
> What about Nova 2.2 ?

Haha, didn't notice Nova 2.2 just released. Should be ok with the correction

**Comment by ebess** [comment]
@ragingdave I don't think there are any PHP 7.1 vs 7.2 issues in this package. So, if the laravel 6.0 is picked, it will come with it's own php version constraint. I guess `>=7.1` should work out, shouldn't it?

**Comment by nemrutco** [comment]
should be ok now (hopefully) haha. Sorry, too many version changes these days since release of laravel 6

**Comment by patrickbrouwers** [comment]
`^2.0` already includes `2.2, so no need to add them as well

**Comment by charlielangridge** [comment]
Please merge - waiting with baited breath!

**Comment by tharindu-abans** [comment]
@ebess hope this will get merged soon. Unable to upgrade to Laravel 6 without this.

**Comment by marky291** [comment]
Awaiting this, thanks :)

**Pull request merged**
