### PR TITLE
Vapor support

### PR DESCRIPTION
**Pull request by harmenjanssen**
I've added support for Vapor, or more broadly, uploading files client-side to S3.   

---

The problem with hosting on Vapor is that [Amazon ApiGateway will not accept POST payloads over 10MB](https://stackoverflow.com/questions/46358922/request-payload-limit-with-aws-api-gateway). The request won't even end up in your app, so even throwing an exception or logging the error won't be possible.

This solution circumvents that by sending the file to S3 client-side, by using a pre-signed URL.

Nova itself supports this using [the VaporFile field](https://nova.laravel.com/docs/3.0/resources/fields.html#vapor-file-field), but of course that's a fairly bare-bones solution without cropping or Spatie's Media Library support.

But I was able to peek in the source code of Nova and base most of the changes in this PR on their native code.

**This addresses and fixes these issues:**

- https://github.com/ebess/advanced-nova-media-library/issues/251
- https://github.com/ebess/advanced-nova-media-library/issues/164

**Missing functionality**

- _SingleMediaRules_ are currently not respected when uploading directly to Vapor. This would require replicating Laravel's rules in Javascript.

---

Please let me know if you are interested in merging this and if not, what I should do to make it so.  
For our company this opens the door to hosting Laravel Nova CMSes on Vapor, which will greatly speed up development.

Thanks!

### CODE REVIEW

**Comment by bkintanar** [comment]
Will spend some time to review this tonight.

--
Bertrand Kintanar
***@***.***

**Comment by HammenWS** [comment]
Awesome!

**Comment by numeralsix** [comment]
Holy crap, thank you.

**Comment by mrbenosborne** [comment]
Hey, we have hit an issue running on Vapor using Load Balancer, see issue https://github.com/ebess/advanced-nova-media-library/issues/287

**Comment by michaelchora** [comment]
@harmenjanssen is there a configuration guide for getting this to work?

**Comment by harmenjanssen** [comment]
@michaelchora You can chain `->uploadsToVapor()` to the field configuration in your Nova resource. Other than that this uses your existing Media Library settings to connect to S3, so no extra config required there.

**Comment by kylekanderson** [comment]
@harmenjanssen this `uploadsToVapor()` method seems to break the `customProperties()` method on the field. When I hard-code custom properties, such as:

```
->customProperties([
    'lorem' => 'ipsum'
])
```

Those custom properties are not persisted to the Media object when I chain the `uploadsToVapor()` method on my field (they are persisted locally, when not using the `uploadsToVapor()` method).

**Comment by didix16** [comment]
Hi guys! This improvement is awesome, just what I looking for, One thing missing tho, I think the README should be updated with the adition of this feature. I just have found this functionality because I looked through the vendor's code, which is not the best practice to see what a package can do. So It will be really helpful if README file updates with this feature.

Thank you so much!

**Pull request merged**
