### PR TITLE
Full Nova 4 compatibility

### PR DESCRIPTION
**Pull request by mucenica-bogdan**
- [x] upgrade de laravel-mix v6
- [x] deleted laravel-nova dependency
- [x] update npm dependecies to work with Vue v3
- [x] update breaking vue3 changes in codebase (mostly v-model)
- [x] replace [vuejs-clipper](https://www.npmjs.com/package/vuejs-clipper) with [vue-advanced-cropper](https://www.npmjs.com/package/vue-advanced-cropper) for vue3 support -> as I couldn't find any easy way to rotate at a set angle with `vue-advanced-cropper`, I replaced the slider with two buttons to rotate by 90degs in either way.
- [x] update draggable to version 4 for Vue v3 support, and changed the markup accordingly 
- [x] fix existing media picker modal 
- [x] fix custom properties modal
- [x] fix various classes not available in `tailwindcss` v3
- [x] prod build

From my tests everything works fine. The only things I haven't test is the Vapor integration.

### CODE REVIEW

**Comment by bkintanar** [comment]
@mucenica-bogdan can you squash your commits please?

**Comment by mucenica-bogdan** [comment]
@bkintanar - sure thing, squash done.

**Comment by bkintanar** [comment]
Can you add notes in the Readme with regards to the vue clipper being replaced?

--
Bertrand Kintanar
***@***.***

**Comment by mucenica-bogdan** [comment]
Sure thing, I'll add in the release notes. 

Thinking of the wording for this, made me release that this new vue3 patch will break compatibility with nova <= v3.

How do plan to release this? New major version maybe, v4.0? If so than we can update the readme to point people to the right version of `advanced-nova-media-library` based on `nova` version. 

What do you think?

**Comment by mucenica-bogdan** [comment]
@bkintanar - if you go with a major version update approach (to v4), I've already pushed in a `change log` section to readme. see https://github.com/ebess/advanced-nova-media-library/blob/d34960995e7522d309c8dc5bfc4b7eacf47a357a/readme.md#change-log

**Comment by bkintanar** [comment]
Thank you I will take a look at it once I am on the computer.

--
Bertrand Kintanar
***@***.***

**Comment by profd2004** [comment]
any update on this?

**Comment by bkintanar** [comment]
Will do a release later today.

**Comment by SupchickCode** [comment]
we are waiting for it =)

**Comment by profd2004** [comment]
Thanks everyone!

Now where's the beer tap? 
How can by you, @bkintanar and @mucenica-bogdan, beers?

**Comment by bkintanar** [comment]
@mucenica-bogdan, @SupchickCode can anyone of you test the latest release and report back please?

**Comment by harlekoy** [comment]
The PR looks good after I tested it on my local. However, for viewing the file within the details page it says `[object Object]`. I'm using `Files::make('Single File')` in my case. :)

**Comment by bkintanar** [comment]
@mucenica-bogdan, when you do your own testing tonight, can you take a look on that single file issue @harlekoy posted?

**Comment by mucenica-bogdan** [comment]
@bkintanar - created a PR for a bugfix patch: https://github.com/ebess/advanced-nova-media-library/pull/321

also, this PR might not be relevant any longer: https://github.com/ebess/advanced-nova-media-library/pull/315

**Pull request merged**
