### PR TITLE
Support for Laravel 7, Nova 3, Spatie Media Library 8

### PR DESCRIPTION
**Pull request by bkintanar**

### CODE REVIEW

**Comment by techdaddies-kevin** [comment]
@ebess Can we get this merged in? I've tested locally and it appears to work perfectly with Laravel 7, Nova 3, and Media Library 8.

**Comment by bkintanar** [comment]
Thanks for testing it out @techdaddies-kevin

**Comment by bkintanar** [comment]
For the time being you can pull my PR by modifying your composer.json file as stated below.

```json
...

"repositories": [
        {
            "type": "path",
            "url": "./nova"
        },
        {
            "type": "vcs",
            "url": "https://github.com/bkintanar/advanced-nova-media-library"
        }
    ],

...
"require": {
        "php": "^7.4",
        "ebess/advanced-nova-media-library": "*",

        "fideloper/proxy": "^4.2",


...
```

**Comment by techdaddies-kevin** [comment]
@bkintanar One *VERY* small thing with this - If you are storing your images on a private disk, the download and crop tools will no longer function correctly. Medialibrary 8 gives us the ability to store the original image on a private disk and the conversions on the public disk, which is working great and is working great with this library, but the download isn't functioning. Not a big deal, but something we need to probably fix.

```php
Images::make('Main Image', 'main')
                ->conversionOnDetailView('thumb')
                ->conversionOnIndexView('thumb')
                ->conversionOnForm('thumb')
                ->fullSize()
                ->rules('required')
```

```php
$this->addMediaCollection('main')
            ->useDisk('products')
            ->storeConversionsOnDisk('public')
            ->singleFile()
            ->registerMediaConversions(function (Media $media) {
                $this->addMediaConversion('thumb')
                    ->width(100)
                    ->height(100);
            });
```

**Comment by bkintanar** [comment]
@techdaddies-kevin thank you for reporting. I'll check if I can replicate and fix the issue.

**Comment by techdaddies-kevin** [comment]
@bkintanar I don't necessarily think it's an issue related to your PR. Rather, I think advanced-nova-media-library itself assumes that the file will be public. I think the DownloadController probably just needs to be updated to proxy the image if it's not public so that it can be shown/downloaded.

**Comment by bkintanar** [comment]
@techdaddies-kevin what's the entry for the private disk like? Just a normal s3 bucket?

**Comment by techdaddies-kevin** [comment]
It's just a local disk in the storage dir.

**Comment by hyperized** [comment]
Can confirm this PR works for me :)

**Comment by bkintanar** [comment]
@techdaddies-kevin OK. I'm trying to replicate the issue. Can you give a steps?

**Comment by techdaddies-kevin** [comment]
All I did was create a new filesystem

```php
'products' => [
            'driver' => 'local',
            'root' => storage_path('products')
        ],
```

From there, all I did was add the conversions and Image fields as described in my post above.

**Comment by bkintanar** [comment]
@techdaddies-kevin I've tested it and downloading images from the the view or edit screens work. It looks like only the crop feature isn't working. Can you confirm on your end? For the meantime I'll try to get a fix.

**Comment by bkintanar** [comment]
@techdaddies-kevin on second thought:

1. Clicking the download icon work.
2. Clicking the crop icon doesn't work.
3. Clicking the magnifying glass icon doesn't work.

**Comment by bkintanar** [comment]
@techdaddies-kevin did you read the docs for Generating custom urls?

https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/generating-custom-urls/#main

I believe you need to write more codes when implementing private storages.

**Comment by techdaddies-kevin** [comment]
Ah, you might be right about that. Maybe just need to create the URL generator for them. That's not something we've needed for our project, but it makes sense that we'd need to create one for this feature to work correctly. Thanks for the idea!

**Comment by SquareBeard** [comment]
There is still a reference to an old v7 class in `src/Fields/Media.php`.
You can remove `use Spatie\MediaLibrary\HasMedia\HasMediaTrait;`, it is not used anyway.

**Comment by ziming** [comment]
my own experience is you need to create a temporary link if is a private disk for it to work

**Comment by dinandmentink** [comment]
Any word from the package maintainer? I'm waiting for this to upgrade a few laravel applications.

**Comment by bkintanar** [comment]
@dinandmentink you can change the composer.json to point to my repository as mentioned above https://github.com/ebess/advanced-nova-media-library/pull/158#issuecomment-597579120

**Comment by RespectPick** [comment]
@bkintanar Could you help me? I did as you said but I got an error during composer update

`  Problem 1
    - ebess/advanced-nova-media-library dev-dependabot/npm_and_yarn/mixin-deep-1.3.2 requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library dev-dependabot/npm_and_yarn/lodash-4.17.15 requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library 2.9.0 requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library 2.9.1 requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library dev-master requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library dev-dependabot/npm_and_yarn/mixin-deep-1.3.2 requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library dev-dependabot/npm_and_yarn/lodash-4.17.15 requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library dev-dependabot/npm_and_yarn/acorn-6.4.1 requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library 2.9.1 requires laravel/nova ^2.0 -> no matching package found.
    - ebess/advanced-nova-media-library 2.9.0 requires laravel/nova ^2.0 -> no matching package found.
    - Conclusion: don't install ebess/advanced-nova-media-library 2.8.0
`

my composer.json

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.4",
        "ext-json": "*",
        "ext-curl": "*",
        "64robots/nova-date-filter": "^0.1.1",
        "barryvdh/laravel-dompdf": "^0.8.4",
        "benjaminhirsch/nova-slug-field": "^1.1",
        "bissolli/nova-phone-field": "^0.0.2",
        "coderello/laravel-nova-lang": "^1.0",
        "doctrine/dbal": "^2.9",
        "eminiarts/nova-tabs": "*",
        "facade/ignition": "^2.0",
        "fideloper/proxy": "^4.0",
        "fntr/BelongsToJudges": "*",
        "fntr/ChampionshipCard": "*",
        "fntr/ChampionshipDates": "*",
        "fntr/PlayerCard": "*",
        "fntr/UserCard": "*",
        "fntr/checkboxes": "*",
        "fntr/competitors": "*",
        "fntr/locations": "*",
        "fntr/passport-tour": "*",
        "fntr/protocol": "*",
        "fntr/results": "*",
        "fntr/schedule": "*",
        "fntr/upload-ratio": "*",
        "laravel/framework": "^7.0",
        "laravel/helpers": "^1.1",
        "laravel/nova": "*",
        "laravel/tinker": "^2.0",
        "numaxlab/nova-ckeditor5-classic": "^1.0",
        "outhebox/nova-hidden-field": "^1.0",
        "ebess/advanced-nova-media-library": "*",
        "phpoffice/phpspreadsheet": "^1.7",
        "predis/predis": "^1.1",
        "ratchet/pawl": "^0.3.4",
        "react/http": "^0.8.5",
        "silvanite/novafieldcheckboxes": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.5",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5",
        "squizlabs/php_codesniffer": "3.*"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        },
        "files": ["app/Functions/functions.php"]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "repositories": [
        {
            "type": "path",
            "url": "./nova"
        },
        {
            "type": "path",
            "url": "./nova-components/Checkboxes"
        },
        {
            "type": "path",
            "url": "./nova-components/BelongsToJudges"
        },
        {
            "type": "path",
            "url": "./nova-components/Competitors"
        },
        {
            "type": "path",
            "url": "./nova-components/Schedule"
        },
        {
            "type": "path",
            "url": "./nova-components/Results"
        },
        {
            "type": "path",
            "url": "./nova-components/ChampionshipDates"
        },
        {
            "type": "path",
            "url": "./nova-components/Locations"
        },
        {
            "type": "path",
            "url": "./nova-components/ChampionshipCard"
        },
        {
            "type": "path",
            "url": "./nova-components/UserCard"
        },
        {
            "type": "path",
            "url": "./nova-components/PlayerCard"
        },
        {
            "type": "path",
            "url": "./nova-components/Protocol"
        },
        {
            "type": "path",
            "url": "./nova-components/PassportTour"
        },
        {
            "type": "path",
            "url": "./nova-components/UploadRatio"
        },
        {
            "type": "vcs",
            "url": "https://github.com/bkintanar/advanced-nova-media-library"
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true
}

```

**Comment by thijsbouwes** [comment]
@RespectPick i had the same issue. Make sure that `nova/composer.json` contains `  "version": "3.1.0"`.

**Comment by RespectPick** [comment]
@thijsbouwes It didn't contains any rows with "version". But event after I had added it i got the same issue

**Comment by bkintanar** [comment]
@RespectPick 

I'm not sure why yours is requiring the following packages:

```
dev-dependabot/npm_and_yarn/mixin-deep-1.3.2 requires laravel/nova ^2.0
dev-dependabot/npm_and_yarn/lodash-4.17.15 requires laravel/nova ^2.0
```

If you can fix those, I believe the error would go away.

**Comment by dinandmentink** [comment]
> @dinandmentink you can change the composer.json to point to my repository as mentioned above [#158 (comment)](https://github.com/ebess/advanced-nova-media-library/pull/158#issuecomment-597579120)

Thanks for the reply. I can indeed already upgrade, but I always feel a bit worried when a package that I use a lot doesn't get these types of updates anymore.

**Comment by NormanHuth** [comment]
> For the time being you can pull my PR by modifying your composer.json file as stated below.
> 
> ```json
> ...
> 
> "repositories": [
>         {
>             "type": "path",
>             "url": "./nova"
>         },
>         {
>             "type": "vcs",
>             "url": "https://github.com/bkintanar/advanced-nova-media-library"
>         }
>     ],
> 
> ...
> "require": {
>         "php": "^7.4",
>         "ebess/advanced-nova-media-library": "*",
> 
>         "fideloper/proxy": "^4.2",
> 
> 
> ...
> ```

Can You bring back the "disk"-Support form der original Version in Your Folk?

**Comment by bkintanar** [comment]
Published it to packagist. You can require `bkintanar/advanced-nova-media-library`.

Until the author makes contact, I'll try to maintain the fork.

Thanks!

**Comment by muhghazaliakbar** [comment]
Thank you @bkintanar

**Comment by VeeeneX** [comment]
@bkintanar Thank you, what about current issues? I saw that you disabled issues on forked repo, should every new PR be opened on that repo so when the author makes contact, you can merge it here?

**Comment by ksassnowski** [comment]
@ebess That merge changed the package name in the `composer.json`. Probably not want you wanted.

**Comment by ksassnowski** [comment]
Nevermind, you already fixed it :)

**Comment by ksassnowski** [comment]
For everyone subscribed to this ticket: These changes have been merged into the `3.0.0` release. @bkintanar I think we can close this issue? Thanks a lot for your work (and fork) and thanks @ebess for merging it

**Pull request merged**
