### PR TITLE
Feature/enforce cropping

### PR DESCRIPTION
**Pull request by danielztolnai**
This PR is mainly a rebase of @GarethSomers' work (see #129) to be merge-able to the current state of the package.

The differences:
- The `Update` button is automatically focused so the user can press `enter` to apply the crop selection
- Cancelling the crop is still allowed when `mustCrop` is set. (So that the user is not 'stuck on the crop screen' by accident)
  - If the image is already uploaded (and cropped), cancelling will result in keeping the previous version of the image
  - If the image is new (and not cropped yet), the cancel button is not shown, but pressing `esc` applies the current crop selection and closes the crop popup.

### CODE REVIEW

**Comment by kukukk** [comment]
Any chance to get this merged?

**Comment by bkintanar** [comment]
@danielztolnai can you fix the conflicts so that I can check and merge?

**Comment by danielztolnai** [comment]
> @danielztolnai can you fix the conflicts so that I can check and merge?

The conflicts are fixed. Sorry, a rebase would've taken too much time because of the conflicts, so I just reverse-merged.

**Comment by bkintanar** [comment]
@danielztolnai no worries. Thanks!

**Comment by bkintanar** [comment]
@danielztolnai sorry. can you add a section in readme on how to use this feature?

**Comment by danielztolnai** [comment]
@bkintanar, of course, I added a few words and an example.

**Comment by bkintanar** [comment]
thanks @danielztolnai will create a tag and release.

**Comment by ebess** [comment]
@bkintanar 
Thanks for handling the PRs. Be aware, you will need to recompile the frontend/vue component after you merged all proper PRs.

**Comment by bkintanar** [comment]
@ebess thanks for the reminder. good to have you here again. :D

**Comment by kukukk** [comment]
Sorry for the pressure, but when can we expect this feature to be released?

**Comment by bkintanar** [comment]
@kukukk Just released a new tag for it.

**Pull request merged**
