### PR TITLE
Fix icons on Files field

### PR DESCRIPTION
**Pull request by potsky**
Hi !

The delete button has disappeared on the `Files` class.

Here is the code with the `Images` class where the delete button is shown:
Images

Here is the code with the `Files` class where the delete button is not shown:
Files

### CODE REVIEW

**Comment by bkintanar** [comment]
@potsky can you do a build and include the dist files in your PR please?

**Comment by potsky** [comment]
> @potsky can you do a build and include the dist files in your PR please?

Hi @bkintanar ! with pleasure but it seems the actual code does not build...

Any idea or hint ?

```
> @ production ~/Desktop/advanced-nova-media-library
> mix --production


✖ Mix
  Compiled with some errors in 678.69ms

ERROR in ./resources/js/components/fields/DetailField.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read property 'styles' of undefined
    at Object.loader (~/Desktop/advanced-nova-media-library/node_modules/vue-loader/dist/index.js:70:34)

ERROR in ./resources/js/components/fields/FormField.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read property 'styles' of undefined
    at Object.loader (~/Desktop/advanced-nova-media-library/node_modules/vue-loader/dist/index.js:70:34)

ERROR in ./resources/js/components/fields/IndexField.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read property 'styles' of undefined
    at Object.loader (~/Desktop/advanced-nova-media-library/node_modules/vue-loader/dist/index.js:70:34)
```

**Comment by potsky** [comment]
> @potsky can you do a build and include the dist files in your PR please?

Hi @bkintanar, it seems the project does not compile anymore. There is no lock file for `package.json` :-( BTW the current dependencies are incorrect. `"vue-loader": "^16.2.0"` [is incompatible](https://stackoverflow.com/questions/74115950/vue-loader-17-0-0-webpack-5-74-0-module-build-failed) with `"vue": "^2.5.17"`, we need to keep `"vue-loader": "^15.0.0"`... I'll try to fix the packages and ship a working lock file.

**Comment by OwlHowl3** [comment]
@potsky @bkintanar Thanks!

**Comment by ziming** [comment]
@bkintanar can tag a release?

**Comment by bkintanar** [comment]
@ziming sorry got busy and forgot. Done now.

**Pull request merged**
