### PR TITLE
Add support for laravel 7 & Nova 3

### PR DESCRIPTION
**Pull request by rompetomp**

### CODE REVIEW

**Comment by muhghazaliakbar** [comment]
@ebess Please merge the PR :)

**Comment by IMPMAC** [comment]
I don't know if this a good thing to do. But as a temporary measure. I adjusted my composer.json to have to following:

`"laravel/framework": "7.0.8 as 6.18.0",`
`"laravel/nova": "3.0.2 as 2.12.0",`

I was then allowed to install the package as usual.

**Comment by jon-sm** [comment]
For anyone wondering, in composer.json, in **repositories**:
```
{
    "type": "vcs",
    "url": "https://github.com/rompetomp/advanced-nova-media-library"
}
```
In **require**:

```
"ebess/advanced-nova-media-library": "dev-laravel-7",
```
will work for now, as it will make composer fetch this branch

**Comment by cloudstudio** [comment]
@ebess could be nice :)

**Comment by bkintanar** [comment]
This does work anymore since spatie removed v7 and changed it to v8. The composer require needs to be modified as well.

**Comment by bkintanar** [comment]
added spatie media library 8 support #158

**Comment by ijpatricio** [comment]
@bkintanar thank you, just installed and used, seems working OK ;) 

everyone who needs some guidance:

in composer.json, add the fork repository as a source, `https://github.com/bkintanar/advanced-nova-media-library`


and then require the original package name, with version `dev-master#ab352886f1ec1363a5e45fa3c488284576d8a397`

```
...

"repositories": [
        {
            "type": "path",
            "url": "./nova"
        },
        {
            "type": "vcs",
            "url": "https://github.com/bkintanar/advanced-nova-media-library"
        }
    ],

...
"require": {
        "php": "^7.4",
        "ebess/advanced-nova-media-library": "dev-master#ab352886f1ec1363a5e45fa3c488284576d8a397",

        "fideloper/proxy": "^4.2",


...

```

Hope it helps someone!

**Comment by bkintanar** [comment]
Thanks @ijpatricio. But that require entry seems to be a mouthful you can just change that to

`"ebess/advanced-nova-media-library": "*"`

**Comment by duckzland** [comment]
confirmed this is working

**Comment by JulianMar** [comment]
@ebess can you merge this?

**Comment by Christophvh** [comment]
@rompetomp Maybe close this one? Since #158 already exists and contains more necessary changes.

**Pull request closed without merging**
