### PR TITLE
Add collection filter for enableExistingMedia

### PR DESCRIPTION
**Pull request by DanielLavoie90**
Add the possibility to specify a collection when using the enableExistingMedia function.
By default the option is null and return all existing media but if you specify a collection, it returns only medias from that collection.

### CODE REVIEW

**Comment by bkintanar** [comment]
@DanielLavoie90 can you add information in the readme for this feature as well please?

**Comment by DanielLavoie90** [comment]
Now that i'm looking at it, I think it would be better to have a filter options instead of separate options for future development. It would reduce the props needed.

**Comment by bkintanar** [comment]
@DanielLavoie90 sounds like a better thing to do indeed. are you willing to create a PR for that so I can delay this PR of yours?

**Comment by DanielLavoie90** [comment]
I can look at it today but i'm not sure on the format those filters should have.
Maybe a filters function that takes an array of arrays
`->filters([
`    ['collection_name, '=', 'collection'],
`    ...
`])
And then apply them with a foreach... 
Or more specific with the function ('where', 'whereNotNull', etc) and with associative arrays?

**Comment by DanielLavoie90** [comment]
Switch to more generic filters in #197

**Pull request closed without merging**
