### PR TITLE
Add support for Laravel 8

### PR DESCRIPTION
**Pull request by adriaanzon**

### CODE REVIEW

**Comment by canvural** [comment]
`spatie/laravel-medialibrary` 8.7.1 is released with Laravel 8. So this PR should be good to go :+1:

**Comment by AlexVanderbist** [comment]
We're also waiting for it over at spatie 😅

**Comment by manojo123** [comment]
Yes please release the support for Laravel 8

**Comment by bkintanar** [comment]
Spatie already supports L8.

**Comment by manojo123** [comment]
Please create a new tag to avoid using dev-master

**Pull request merged**
