### PR TITLE
Upgrade to vuejs-clipper 2.1.2 to support init-* props

### PR DESCRIPTION
**Pull request by danielztolnai**
The newer vuejs-clipper has more features, for example `initHeight` and `initWidth` to allow setting the initial size of the cropped image.

This can be used to allow the user to clip a precisely 100% width or height image.
```php
Images::make('Gallery')->croppingConfigs(['ratio' => 4/3, 'initHeight' => 100, 'initWidth' => 100])
```

### CODE REVIEW

**Comment by bkintanar** [comment]
@danielztolnai kindly add the description to the readme.

**Comment by danielztolnai** [comment]
@bkintanar I think this is already present in this section: https://github.com/ebess/advanced-nova-media-library#image-cropping
There is a link to the vuejs-clipper readme, this one: https://github.com/timtnleeProject/vuejs-clipper#clipper-basic

**Comment by danielztolnai** [comment]
@bkintanar, now that I checked, pull request #243 upgrades to an even newer vuejs-clipper, so that upgrade is preferred to this one if you can get that one merged.

**Comment by bkintanar** [comment]
@danielztolnai I see it. but I'm still waiting for the PR creator to update it.

**Comment by danielztolnai** [comment]
I see that #243 got merged, so vuejs-clipper is even newer. :-) Closing this one.

**Pull request closed without merging**
